name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - run: docker build -t ergaru1/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ergaru1/react-test npm test

      - run: docker build -t ergaru1/multi-client ./client
      - run: docker build -t ergaru1/multi-nginx ./nginx
      - run: docker build -t ergaru1/multi-server ./server
      - run: docker build -t ergaru1/multi-worker ./worker

      - run: docker push ergaru1/multi-client
      - run: docker push ergaru1/multi-nginx
      - run: docker push ergaru1/multi-server
      - run: docker push ergaru1/multi-worker
